### ISSUE TITLE
Paste Google Maps coordinates from clipboard on load

### ISSUE THREAD

**Issue by lgarczewski** [wikimedia-pl/geo4wiki#1]
Paste from cliboard and submit form.

Only do this if clipboard contents match decimal coordinates regexp.

docs: https://web.dev/async-clipboard/#readtext()

**Comment by PeterBowman** [comment]
> docs: https://web.dev/async-clipboard/#readtext()

Per https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility:

> Firefox only supports reading the clipboard in browser extensions, using the "clipboardRead" extension permission.

Attempting to query the `clipboard-read` permission on Firefox 87.0 will result in a similar error as the one reported [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1560373). Sadly, it looks like clipboard read/write permissions might never land on Firefox due to security concerns:

> Firefox (and Safari as well, per standards discussions) are pushing back against clipboard-write as there is no good way to offer this functionality with informed user consent. It's being removed from the specification.

Accessing the clipboard through the old and deprecated API is documented [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard), and [this SO answer](https://stackoverflow.com/a/6804718/10404307) provides a working solution using *paste* event handlers (which doesn't make sense in our use case). I'm afraid accessing clipboard contents on demand (specifically on page load) is regarded as kinda intrusive, therefore it lacks proper support for the time being.

**Comment by PeterBowman** [comment]
By the way, would you mind changing this regex:

https://github.com/wikimedia-pl/geo4wiki/blob/4c1e6434ff13614b7ce046c04572bc8c390fd07b/index.html#L19

into: `pattern="-?[0-9]+(\.[0-9]+)?, ?-?[0-9]+(\.[0-9]+)?"` (just adding <code>&nbsp;?</code> around the middle)? Google Maps insists on placing a space character between the coordinates.

**Comment by lgarczewski** [comment]
Thanks for investigating, closing this.

Added the space as requested in https://github.com/wikimedia-pl/geo4wiki/commit/058ce5b2164759198003bc84f523d6fbbf2afb6f
